//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEDICOM
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CFDiException
    {
        
        private int codField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cod
        {
            get
            {
                return this.codField;
            }
            set
            {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", ConfigurationName="ServicioEDICOM.CFDi")]
    public interface CFDi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiResponse> getTimbreCfdiAsync(ServicioEDICOM.getTimbreCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiTestResponse> getTimbreCfdiTestAsync(ServicioEDICOM.getTimbreCfdiTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiTestResponse> getCfdiTestAsync(ServicioEDICOM.getCfdiTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesSignedResponse> cancelaCFDiRetencionesSignedAsync(ServicioEDICOM.cancelaCFDiRetencionesSignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesTestResponse> getCfdiRetencionesTestAsync(ServicioEDICOM.getCfdiRetencionesTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesResponse> getTimbreCfdiRetencionesAsync(ServicioEDICOM.getTimbreCfdiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesTestResponse> getTimbreCfdiRetencionesTestAsync(ServicioEDICOM.getTimbreCfdiRetencionesTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesResponse> cancelaCFDiRetencionesAsync(ServicioEDICOM.cancelaCFDiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getUUIDTestResponse> getUUIDTestAsync(ServicioEDICOM.getUUIDTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiFromUUIDResponse> getCfdiFromUUIDAsync(ServicioEDICOM.getCfdiFromUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiAckResponse> getCfdiAckAsync(ServicioEDICOM.getCfdiAckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtResponse> getCfdiExtAsync(ServicioEDICOM.getCfdiExtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtTestResponse> getCfdiExtTestAsync(ServicioEDICOM.getCfdiExtTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.exportCfdiResponse> exportCfdiAsync(ServicioEDICOM.exportCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCFDiStatusReturn")]
        System.Threading.Tasks.Task<ServicioEDICOM.CancelQueryData> getCFDiStatusAsync(string user, string password, string rfcE, string rfcR, string uuid, double total, bool test);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiResponse> cancelaCFDiAsync(ServicioEDICOM.cancelaCFDiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiSignedResponse> cancelaCFDiSignedAsync(ServicioEDICOM.cancelaCFDiSignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiAsyncResponse> cancelCFDiAsyncAsync(ServicioEDICOM.cancelCFDiAsyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiSignedAsyncResponse> cancelCFDiSignedAsyncAsync(ServicioEDICOM.cancelCFDiSignedAsyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesResponse> getCfdiRetencionesAsync(ServicioEDICOM.getCfdiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiResponse> getCfdiAsync(ServicioEDICOM.getCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServicioEDICOM.getUUIDResponse> getUUIDAsync(ServicioEDICOM.getUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServicioEDICOM.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        System.Threading.Tasks.Task<bool> changePasswordAsync(string user, string password, string newPassword);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRequest()
        {
        }
        
        public getTimbreCfdiRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiReturn;
        
        public getTimbreCfdiResponse()
        {
        }
        
        public getTimbreCfdiResponse(byte[] getTimbreCfdiReturn)
        {
            this.getTimbreCfdiReturn = getTimbreCfdiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiTestRequest()
        {
        }
        
        public getTimbreCfdiTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiTestReturn;
        
        public getTimbreCfdiTestResponse()
        {
        }
        
        public getTimbreCfdiTestResponse(byte[] getTimbreCfdiTestReturn)
        {
            this.getTimbreCfdiTestReturn = getTimbreCfdiTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiTestRequest()
        {
        }
        
        public getCfdiTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiTestReturn;
        
        public getCfdiTestResponse()
        {
        }
        
        public getCfdiTestResponse(byte[] getCfdiTestReturn)
        {
            this.getCfdiTestReturn = getCfdiTestReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CancelaResponse
    {
        
        private string ackField;
        
        private string textField;
        
        private string[] uuidsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ack
        {
            get
            {
                return this.ackField;
            }
            set
            {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] uuids
        {
            get
            {
                return this.uuidsField;
            }
            set
            {
                this.uuidsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesSigned", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesSignedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        public bool test;
        
        public cancelaCFDiRetencionesSignedRequest()
        {
        }
        
        public cancelaCFDiRetencionesSignedRequest(string user, string password, byte[] sign, bool test)
        {
            this.user = user;
            this.password = password;
            this.sign = sign;
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesSignedResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesSignedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelaResponse cancelaCFDiRetencionesSignedReturn;
        
        public cancelaCFDiRetencionesSignedResponse()
        {
        }
        
        public cancelaCFDiRetencionesSignedResponse(ServicioEDICOM.CancelaResponse cancelaCFDiRetencionesSignedReturn)
        {
            this.cancelaCFDiRetencionesSignedReturn = cancelaCFDiRetencionesSignedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRetencionesTestRequest()
        {
        }
        
        public getCfdiRetencionesTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiRetencionesTestReturn;
        
        public getCfdiRetencionesTestResponse()
        {
        }
        
        public getCfdiRetencionesTestResponse(byte[] getCfdiRetencionesTestReturn)
        {
            this.getCfdiRetencionesTestReturn = getCfdiRetencionesTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRetencionesRequest()
        {
        }
        
        public getTimbreCfdiRetencionesRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiRetencionesReturn;
        
        public getTimbreCfdiRetencionesResponse()
        {
        }
        
        public getTimbreCfdiRetencionesResponse(byte[] getTimbreCfdiRetencionesReturn)
        {
            this.getTimbreCfdiRetencionesReturn = getTimbreCfdiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRetencionesTestRequest()
        {
        }
        
        public getTimbreCfdiRetencionesTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiRetencionesTestReturn;
        
        public getTimbreCfdiRetencionesTestResponse()
        {
        }
        
        public getTimbreCfdiRetencionesTestResponse(byte[] getTimbreCfdiRetencionesTestReturn)
        {
            this.getTimbreCfdiRetencionesTestReturn = getTimbreCfdiRetencionesTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public string pfxPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=6)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=7)]
        public string sustitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=8)]
        public bool test;
        
        public cancelaCFDiRetencionesRequest()
        {
        }
        
        public cancelaCFDiRetencionesRequest(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword, string motivo, string sustitucion, bool test)
        {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
            this.pfx = pfx;
            this.pfxPassword = pfxPassword;
            this.motivo = motivo;
            this.sustitucion = sustitucion;
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelaResponse cancelaCFDiRetencionesReturn;
        
        public cancelaCFDiRetencionesResponse()
        {
        }
        
        public cancelaCFDiRetencionesResponse(ServicioEDICOM.CancelaResponse cancelaCFDiRetencionesReturn)
        {
            this.cancelaCFDiRetencionesReturn = cancelaCFDiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getUUIDTestRequest()
        {
        }
        
        public getUUIDTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string getUUIDTestReturn;
        
        public getUUIDTestResponse()
        {
        }
        
        public getUUIDTestResponse(string getUUIDTestReturn)
        {
            this.getUUIDTestReturn = getUUIDTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiFromUUID", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiFromUUIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        public getCfdiFromUUIDRequest()
        {
        }
        
        public getCfdiFromUUIDRequest(string user, string password, string rfc, string[] uuid)
        {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiFromUUIDResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiFromUUIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiFromUUIDReturn;
        
        public getCfdiFromUUIDResponse()
        {
        }
        
        public getCfdiFromUUIDResponse(byte[] getCfdiFromUUIDReturn)
        {
            this.getCfdiFromUUIDReturn = getCfdiFromUUIDReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiAck", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiAckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        public getCfdiAckRequest()
        {
        }
        
        public getCfdiAckRequest(string user, string password, string[] uuid)
        {
            this.user = user;
            this.password = password;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiAckResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiAckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiAckReturn;
        
        public getCfdiAckResponse()
        {
        }
        
        public getCfdiAckResponse(byte[] getCfdiAckReturn)
        {
            this.getCfdiAckReturn = getCfdiAckReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiExt", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiExtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiExtRequest()
        {
        }
        
        public getCfdiExtRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiExtResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiExtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiExtReturn;
        
        public getCfdiExtResponse()
        {
        }
        
        public getCfdiExtResponse(byte[] getCfdiExtReturn)
        {
            this.getCfdiExtReturn = getCfdiExtReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiExtTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiExtTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiExtTestRequest()
        {
        }
        
        public getCfdiExtTestRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiExtTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiExtTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiExtTestReturn;
        
        public getCfdiExtTestResponse()
        {
        }
        
        public getCfdiExtTestResponse(byte[] getCfdiExtTestReturn)
        {
            this.getCfdiExtTestReturn = getCfdiExtTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class exportCfdiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        public System.DateTime iniDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        public System.DateTime endDate;
        
        public exportCfdiRequest()
        {
        }
        
        public exportCfdiRequest(string user, string password, string rfc, System.DateTime iniDate, System.DateTime endDate)
        {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.iniDate = iniDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class exportCfdiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] exportCfdiReturn;
        
        public exportCfdiResponse()
        {
        }
        
        public exportCfdiResponse(byte[] exportCfdiReturn)
        {
            this.exportCfdiReturn = exportCfdiReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CancelQueryData
    {
        
        private string cancelStatusField;
        
        private string isCancelableField;
        
        private string statusField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cancelStatus
        {
            get
            {
                return this.cancelStatusField;
            }
            set
            {
                this.cancelStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string isCancelable
        {
            get
            {
                return this.isCancelableField;
            }
            set
            {
                this.isCancelableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public string pfxPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=6)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=7)]
        public string sustitucion;
        
        public cancelaCFDiRequest()
        {
        }
        
        public cancelaCFDiRequest(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword, string motivo, string sustitucion)
        {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
            this.pfx = pfx;
            this.pfxPassword = pfxPassword;
            this.motivo = motivo;
            this.sustitucion = sustitucion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelaResponse cancelaCFDiReturn;
        
        public cancelaCFDiResponse()
        {
        }
        
        public cancelaCFDiResponse(ServicioEDICOM.CancelaResponse cancelaCFDiReturn)
        {
            this.cancelaCFDiReturn = cancelaCFDiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiSigned", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiSignedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sign;
        
        public cancelaCFDiSignedRequest()
        {
        }
        
        public cancelaCFDiSignedRequest(string user, string password, byte[] sign)
        {
            this.user = user;
            this.password = password;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiSignedResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiSignedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelaResponse cancelaCFDiSignedReturn;
        
        public cancelaCFDiSignedResponse()
        {
        }
        
        public cancelaCFDiSignedResponse(ServicioEDICOM.CancelaResponse cancelaCFDiSignedReturn)
        {
            this.cancelaCFDiSignedReturn = cancelaCFDiSignedReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CancelData
    {
        
        private string ackField;
        
        private CancelQueryData cancelQueryDataField;
        
        private string rfcEField;
        
        private string statusField;
        
        private string statusCodeField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ack
        {
            get
            {
                return this.ackField;
            }
            set
            {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public CancelQueryData cancelQueryData
        {
            get
            {
                return this.cancelQueryDataField;
            }
            set
            {
                this.cancelQueryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string rfcE
        {
            get
            {
                return this.rfcEField;
            }
            set
            {
                this.rfcEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCFDiAsync", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelCFDiAsyncRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfcE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        public string rfcR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public double total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=7)]
        public string pfxPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=8)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=9)]
        public string sustitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=10)]
        public bool test;
        
        public cancelCFDiAsyncRequest()
        {
        }
        
        public cancelCFDiAsyncRequest(string user, string password, string rfcE, string rfcR, string uuid, double total, byte[] pfx, string pfxPassword, string motivo, string sustitucion, bool test)
        {
            this.user = user;
            this.password = password;
            this.rfcE = rfcE;
            this.rfcR = rfcR;
            this.uuid = uuid;
            this.total = total;
            this.pfx = pfx;
            this.pfxPassword = pfxPassword;
            this.motivo = motivo;
            this.sustitucion = sustitucion;
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCFDiAsyncResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelCFDiAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelData cancelCFDiAsyncReturn;
        
        public cancelCFDiAsyncResponse()
        {
        }
        
        public cancelCFDiAsyncResponse(ServicioEDICOM.CancelData cancelCFDiAsyncReturn)
        {
            this.cancelCFDiAsyncReturn = cancelCFDiAsyncReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCFDiSignedAsync", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelCFDiSignedAsyncRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        public string rfcE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        public string rfcR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=6)]
        public double total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=7)]
        public bool test;
        
        public cancelCFDiSignedAsyncRequest()
        {
        }
        
        public cancelCFDiSignedAsyncRequest(string user, string password, byte[] sign, string rfcE, string rfcR, string uuid, double total, bool test)
        {
            this.user = user;
            this.password = password;
            this.sign = sign;
            this.rfcE = rfcE;
            this.rfcR = rfcR;
            this.uuid = uuid;
            this.total = total;
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCFDiSignedAsyncResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelCFDiSignedAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public ServicioEDICOM.CancelData cancelCFDiSignedAsyncReturn;
        
        public cancelCFDiSignedAsyncResponse()
        {
        }
        
        public cancelCFDiSignedAsyncResponse(ServicioEDICOM.CancelData cancelCFDiSignedAsyncReturn)
        {
            this.cancelCFDiSignedAsyncReturn = cancelCFDiSignedAsyncReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRetencionesRequest()
        {
        }
        
        public getCfdiRetencionesRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiRetencionesReturn;
        
        public getCfdiRetencionesResponse()
        {
        }
        
        public getCfdiRetencionesResponse(byte[] getCfdiRetencionesReturn)
        {
            this.getCfdiRetencionesReturn = getCfdiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRequest()
        {
        }
        
        public getCfdiRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiReturn;
        
        public getCfdiResponse()
        {
        }
        
        public getCfdiResponse(byte[] getCfdiReturn)
        {
            this.getCfdiReturn = getCfdiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUID", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getUUIDRequest()
        {
        }
        
        public getUUIDRequest(string user, string password, byte[] file)
        {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string getUUIDReturn;
        
        public getUUIDResponse()
        {
        }
        
        public getUUIDResponse(string getUUIDReturn)
        {
            this.getUUIDReturn = getUUIDReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CFDiChannel : ServicioEDICOM.CFDi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CFDiClient : System.ServiceModel.ClientBase<ServicioEDICOM.CFDi>, ServicioEDICOM.CFDi
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CFDiClient() : 
                base(CFDiClient.GetDefaultBinding(), CFDiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CFDi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CFDiClient(EndpointConfiguration endpointConfiguration) : 
                base(CFDiClient.GetBindingForEndpoint(endpointConfiguration), CFDiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CFDiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CFDiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CFDiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CFDiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CFDiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiResponse> ServicioEDICOM.CFDi.getTimbreCfdiAsync(ServicioEDICOM.getTimbreCfdiRequest request)
        {
            return base.Channel.getTimbreCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiResponse> getTimbreCfdiAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getTimbreCfdiRequest inValue = new ServicioEDICOM.getTimbreCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getTimbreCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiTestResponse> ServicioEDICOM.CFDi.getTimbreCfdiTestAsync(ServicioEDICOM.getTimbreCfdiTestRequest request)
        {
            return base.Channel.getTimbreCfdiTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiTestResponse> getTimbreCfdiTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getTimbreCfdiTestRequest inValue = new ServicioEDICOM.getTimbreCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getTimbreCfdiTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiTestResponse> ServicioEDICOM.CFDi.getCfdiTestAsync(ServicioEDICOM.getCfdiTestRequest request)
        {
            return base.Channel.getCfdiTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiTestResponse> getCfdiTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiTestRequest inValue = new ServicioEDICOM.getCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesSignedResponse> ServicioEDICOM.CFDi.cancelaCFDiRetencionesSignedAsync(ServicioEDICOM.cancelaCFDiRetencionesSignedRequest request)
        {
            return base.Channel.cancelaCFDiRetencionesSignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesSignedResponse> cancelaCFDiRetencionesSignedAsync(string user, string password, byte[] sign, bool test)
        {
            ServicioEDICOM.cancelaCFDiRetencionesSignedRequest inValue = new ServicioEDICOM.cancelaCFDiRetencionesSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            inValue.test = test;
            return ((ServicioEDICOM.CFDi)(this)).cancelaCFDiRetencionesSignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesTestResponse> ServicioEDICOM.CFDi.getCfdiRetencionesTestAsync(ServicioEDICOM.getCfdiRetencionesTestRequest request)
        {
            return base.Channel.getCfdiRetencionesTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesTestResponse> getCfdiRetencionesTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiRetencionesTestRequest inValue = new ServicioEDICOM.getCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiRetencionesTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesResponse> ServicioEDICOM.CFDi.getTimbreCfdiRetencionesAsync(ServicioEDICOM.getTimbreCfdiRetencionesRequest request)
        {
            return base.Channel.getTimbreCfdiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesResponse> getTimbreCfdiRetencionesAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getTimbreCfdiRetencionesRequest inValue = new ServicioEDICOM.getTimbreCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getTimbreCfdiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesTestResponse> ServicioEDICOM.CFDi.getTimbreCfdiRetencionesTestAsync(ServicioEDICOM.getTimbreCfdiRetencionesTestRequest request)
        {
            return base.Channel.getTimbreCfdiRetencionesTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getTimbreCfdiRetencionesTestResponse> getTimbreCfdiRetencionesTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getTimbreCfdiRetencionesTestRequest inValue = new ServicioEDICOM.getTimbreCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getTimbreCfdiRetencionesTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesResponse> ServicioEDICOM.CFDi.cancelaCFDiRetencionesAsync(ServicioEDICOM.cancelaCFDiRetencionesRequest request)
        {
            return base.Channel.cancelaCFDiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiRetencionesResponse> cancelaCFDiRetencionesAsync(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword, string motivo, string sustitucion, bool test)
        {
            ServicioEDICOM.cancelaCFDiRetencionesRequest inValue = new ServicioEDICOM.cancelaCFDiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            inValue.motivo = motivo;
            inValue.sustitucion = sustitucion;
            inValue.test = test;
            return ((ServicioEDICOM.CFDi)(this)).cancelaCFDiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getUUIDTestResponse> ServicioEDICOM.CFDi.getUUIDTestAsync(ServicioEDICOM.getUUIDTestRequest request)
        {
            return base.Channel.getUUIDTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getUUIDTestResponse> getUUIDTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getUUIDTestRequest inValue = new ServicioEDICOM.getUUIDTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getUUIDTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiFromUUIDResponse> ServicioEDICOM.CFDi.getCfdiFromUUIDAsync(ServicioEDICOM.getCfdiFromUUIDRequest request)
        {
            return base.Channel.getCfdiFromUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiFromUUIDResponse> getCfdiFromUUIDAsync(string user, string password, string rfc, string[] uuid)
        {
            ServicioEDICOM.getCfdiFromUUIDRequest inValue = new ServicioEDICOM.getCfdiFromUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiFromUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiAckResponse> ServicioEDICOM.CFDi.getCfdiAckAsync(ServicioEDICOM.getCfdiAckRequest request)
        {
            return base.Channel.getCfdiAckAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiAckResponse> getCfdiAckAsync(string user, string password, string[] uuid)
        {
            ServicioEDICOM.getCfdiAckRequest inValue = new ServicioEDICOM.getCfdiAckRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.uuid = uuid;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiAckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtResponse> ServicioEDICOM.CFDi.getCfdiExtAsync(ServicioEDICOM.getCfdiExtRequest request)
        {
            return base.Channel.getCfdiExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtResponse> getCfdiExtAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiExtRequest inValue = new ServicioEDICOM.getCfdiExtRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiExtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtTestResponse> ServicioEDICOM.CFDi.getCfdiExtTestAsync(ServicioEDICOM.getCfdiExtTestRequest request)
        {
            return base.Channel.getCfdiExtTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiExtTestResponse> getCfdiExtTestAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiExtTestRequest inValue = new ServicioEDICOM.getCfdiExtTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiExtTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.exportCfdiResponse> ServicioEDICOM.CFDi.exportCfdiAsync(ServicioEDICOM.exportCfdiRequest request)
        {
            return base.Channel.exportCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.exportCfdiResponse> exportCfdiAsync(string user, string password, string rfc, System.DateTime iniDate, System.DateTime endDate)
        {
            ServicioEDICOM.exportCfdiRequest inValue = new ServicioEDICOM.exportCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.iniDate = iniDate;
            inValue.endDate = endDate;
            return ((ServicioEDICOM.CFDi)(this)).exportCfdiAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.CancelQueryData> getCFDiStatusAsync(string user, string password, string rfcE, string rfcR, string uuid, double total, bool test)
        {
            return base.Channel.getCFDiStatusAsync(user, password, rfcE, rfcR, uuid, total, test);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiResponse> ServicioEDICOM.CFDi.cancelaCFDiAsync(ServicioEDICOM.cancelaCFDiRequest request)
        {
            return base.Channel.cancelaCFDiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiResponse> cancelaCFDiAsync(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword, string motivo, string sustitucion)
        {
            ServicioEDICOM.cancelaCFDiRequest inValue = new ServicioEDICOM.cancelaCFDiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            inValue.motivo = motivo;
            inValue.sustitucion = sustitucion;
            return ((ServicioEDICOM.CFDi)(this)).cancelaCFDiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiSignedResponse> ServicioEDICOM.CFDi.cancelaCFDiSignedAsync(ServicioEDICOM.cancelaCFDiSignedRequest request)
        {
            return base.Channel.cancelaCFDiSignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelaCFDiSignedResponse> cancelaCFDiSignedAsync(string user, string password, byte[] sign)
        {
            ServicioEDICOM.cancelaCFDiSignedRequest inValue = new ServicioEDICOM.cancelaCFDiSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            return ((ServicioEDICOM.CFDi)(this)).cancelaCFDiSignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiAsyncResponse> ServicioEDICOM.CFDi.cancelCFDiAsyncAsync(ServicioEDICOM.cancelCFDiAsyncRequest request)
        {
            return base.Channel.cancelCFDiAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiAsyncResponse> cancelCFDiAsyncAsync(string user, string password, string rfcE, string rfcR, string uuid, double total, byte[] pfx, string pfxPassword, string motivo, string sustitucion, bool test)
        {
            ServicioEDICOM.cancelCFDiAsyncRequest inValue = new ServicioEDICOM.cancelCFDiAsyncRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfcE = rfcE;
            inValue.rfcR = rfcR;
            inValue.uuid = uuid;
            inValue.total = total;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            inValue.motivo = motivo;
            inValue.sustitucion = sustitucion;
            inValue.test = test;
            return ((ServicioEDICOM.CFDi)(this)).cancelCFDiAsyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiSignedAsyncResponse> ServicioEDICOM.CFDi.cancelCFDiSignedAsyncAsync(ServicioEDICOM.cancelCFDiSignedAsyncRequest request)
        {
            return base.Channel.cancelCFDiSignedAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.cancelCFDiSignedAsyncResponse> cancelCFDiSignedAsyncAsync(string user, string password, byte[] sign, string rfcE, string rfcR, string uuid, double total, bool test)
        {
            ServicioEDICOM.cancelCFDiSignedAsyncRequest inValue = new ServicioEDICOM.cancelCFDiSignedAsyncRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            inValue.rfcE = rfcE;
            inValue.rfcR = rfcR;
            inValue.uuid = uuid;
            inValue.total = total;
            inValue.test = test;
            return ((ServicioEDICOM.CFDi)(this)).cancelCFDiSignedAsyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesResponse> ServicioEDICOM.CFDi.getCfdiRetencionesAsync(ServicioEDICOM.getCfdiRetencionesRequest request)
        {
            return base.Channel.getCfdiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiRetencionesResponse> getCfdiRetencionesAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiRetencionesRequest inValue = new ServicioEDICOM.getCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getCfdiResponse> ServicioEDICOM.CFDi.getCfdiAsync(ServicioEDICOM.getCfdiRequest request)
        {
            return base.Channel.getCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getCfdiResponse> getCfdiAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getCfdiRequest inValue = new ServicioEDICOM.getCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioEDICOM.getUUIDResponse> ServicioEDICOM.CFDi.getUUIDAsync(ServicioEDICOM.getUUIDRequest request)
        {
            return base.Channel.getUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioEDICOM.getUUIDResponse> getUUIDAsync(string user, string password, byte[] file)
        {
            ServicioEDICOM.getUUIDRequest inValue = new ServicioEDICOM.getUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((ServicioEDICOM.CFDi)(this)).getUUIDAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> changePasswordAsync(string user, string password, string newPassword)
        {
            return base.Channel.changePasswordAsync(user, password, newPassword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CFDi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CFDi))
            {
                return new System.ServiceModel.EndpointAddress("https://cfdiws.sedeb2b.com/EdiwinWS/services/CFDi");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CFDiClient.GetBindingForEndpoint(EndpointConfiguration.CFDi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CFDiClient.GetEndpointAddress(EndpointConfiguration.CFDi);
        }
        
        public enum EndpointConfiguration
        {
            
            CFDi,
        }
    }
}
