// <auto-generated />
using System;
using ERPSEI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPSEI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPSEI.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("FathersLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MothersLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Asistente Dirección"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Auditoría"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bancos"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Director Administrativo"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Entregables"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Facturación"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Fiscal"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Impuestos"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "IMSS"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Legal"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Nómina"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Nómina Externo"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Operaciones"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Operaciones Internas"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Operaciones Nómina"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Sistemas"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Soporte Dirección"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Tesorería"
                        });
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.ContactoEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ContactosEmergencia", (string)null);
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("NSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PuestoId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosCiviles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Soltero(a)"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Casado(a)"
                        });
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Femenino"
                        });
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Puestos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Analista de IMSS"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Analista de Nómina"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Asistente AC"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Asistente de Dirección"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Asistente de Dirección / Julio"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Asistente de Dirección / Paco"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Asistente de Dirección / Alex"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Auditoría"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Auxiliar de Tesorería"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Auxiliar Administrativo"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Auxiliar Contable"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Auxiliar Contable Austria 6"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Auxiliar Contable Julio"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Auxiliar Contable Nómina Julio"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Auxiliar de Área Legal"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Auxiliar de Auditoría"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Auxiliar de Bancos"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Auxiliar de Entregables"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Auxiliar de Impuestos"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Auxiliar de Nómina"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Auxiliar de Nómina Cancún"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Auxiliar de Recursos Humanos"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Auxiliar de Sistemas"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Auxiliar de Tesorería"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Auxiliar IMSS"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Chofer"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Director Administrativo"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Director General"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Encargado de Impuestos"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Encargado de Contabilidad"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Encargado de IMSS"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Encargado de Nómina"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Facturación"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Gerente de Área Legal"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Gerente de Auditoría"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Gerente de Bancos"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Gerente de Contabilidad"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Gerente de Entregables"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Gerente de Impuestos"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Gerente de Nómina"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Gerente de Operaciones"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Gerente de Operaciones Internas"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Gerente de Recursos Humanos"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Inplant Nóminas/Asimilados"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Mantenimiento y Limpieza"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Nóminas Brame/Asimilados"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Pasante del Área Legal Clarisa"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Recepción Entregables Pafnuncio piso 5"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Recepción Lago de Guadalupe"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Recepción Los Reyes la Paz"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Recepcionista Austria 6"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Recepcionista Big 407"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Recepcionista Big 510"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Recepcionista Izaguirre"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Recepcionista Pirules"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Recepcionista Polanco"
                        },
                        new
                        {
                            Id = 57,
                            Nombre = "Recepcionista Sta Mónica"
                        },
                        new
                        {
                            Id = 58,
                            Nombre = "Recepcionista Torres Esmeralda"
                        },
                        new
                        {
                            Id = 59,
                            Nombre = "Recepcionista y Apoyo Facturación Big 303"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Recepcionista Condor"
                        },
                        new
                        {
                            Id = 61,
                            Nombre = "Senior de Soporte - Desarrollador de Software Izcalli 1"
                        },
                        new
                        {
                            Id = 62,
                            Nombre = "Sistemas"
                        },
                        new
                        {
                            Id = 63,
                            Nombre = "Subencargado de Nómina"
                        },
                        new
                        {
                            Id = 64,
                            Nombre = "Supervisor Contable"
                        },
                        new
                        {
                            Id = 65,
                            Nombre = "Supervisor de Contabilidad"
                        },
                        new
                        {
                            Id = 66,
                            Nombre = "Supervisor Entregables"
                        },
                        new
                        {
                            Id = 67,
                            Nombre = "Supervisor / Encargado de Nómina"
                        },
                        new
                        {
                            Id = 68,
                            Nombre = "Tesorero"
                        });
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acta de nacimiento"
                        },
                        new
                        {
                            Id = 2,
                            Description = "CURP"
                        },
                        new
                        {
                            Id = 3,
                            Description = "CLABE"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comprobante de domicilio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Contactos de emergencia"
                        },
                        new
                        {
                            Id = 6,
                            Description = "CSF"
                        },
                        new
                        {
                            Id = 7,
                            Description = "INE"
                        },
                        new
                        {
                            Id = 8,
                            Description = "RFC"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Comprobante de estudios"
                        },
                        new
                        {
                            Id = 10,
                            Description = "NSS"
                        });
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.UserFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FileTypeId");

                    b.ToTable("UserFiles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.AppUser", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.Empleados.Empleado", "Empleado")
                        .WithOne("User")
                        .HasForeignKey("ERPSEI.Data.Entities.AppUser", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.ContactoEmergencia", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.Empleados.Empleado", "Empleado")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Empleado", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.Empleados.Area", "Area")
                        .WithMany("Empleados")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPSEI.Data.Entities.Empleados.EstadoCivil", "EstadoCivil")
                        .WithMany("Empleados")
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPSEI.Data.Entities.Empleados.Genero", "Genero")
                        .WithMany("Empleados")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPSEI.Data.Entities.Empleados.Puesto", "Puesto")
                        .WithMany("Empleados")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Genero");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.UserFile", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.Empleados.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPSEI.Data.Entities.FileType", "FileType")
                        .WithMany("UserFiles")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPSEI.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERPSEI.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Area", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Empleado", b =>
                {
                    b.Navigation("ContactosEmergencia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.EstadoCivil", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Genero", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.Empleados.Puesto", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ERPSEI.Data.Entities.FileType", b =>
                {
                    b.Navigation("UserFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
